site:
  name: Scheeren Tec GmbH
  site: 'https://scheeren-tec.de'
  base: '/'
  trailingSlash: false

# Default SEO metadata
metadata:
  title:
    default: Scheeren Tec GmbH – Heizungstechnik Heinsberg
    template: '%s — Scheeren Tec GmbH'
  description: 'Heizungstechnik. Modern gedacht. Wärmepumpen, Heizungen & Solar im Kreis Heinsberg – seit 2016. Vaillant Fachpartner & Gebäudeenergieberater HWK.'
  robots:
    index: true
    follow: true
  openGraph:
    site_name: Scheeren Tec GmbH
    images:
      - url: '~/assets/images/default.png'
        width: 1200
        height: 628
    type: website

i18n:
  language: de
  textDirection: ltr

apps:
  blog:
    isEnabled: false
    postsPerPage: 6

    post:
      isEnabled: false
      permalink: '/%slug%'
      robots:
        index: true

    list:
      isEnabled: false
      pathname: 'blog'
      robots:
        index: true

    category:
      isEnabled: false
      pathname: 'category'
      robots:
        index: true

    tag:
      isEnabled: false
      pathname: 'tag'
      robots:
        index: false

    isRelatedPostsEnabled: false
    relatedPostsCount: 4

analytics:
  vendors:
    googleAnalytics:
      id: null

ui:
  theme: 'dark:only'
